name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.17.0

      - working-directory: packages/dart-parser
        run: dart pub get
      - run: npm ci

      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: |
          ls -al node_modules
          ls -al node_modules/@nx-dart
          ls -al node_modules/@nx-dart/dart-parser
      - run: npx nx affected --target=e2e --parallel=3
      - run: npx nx affected --target=build --parallel=3
